// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzonExpress.Data;

#nullable disable

namespace OzonExpress.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230713100808_UpdateTarifColumn")]
    partial class UpdateTarifColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OzonExpress.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Prix")
                        .HasColumnType("real");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("OzonExpress.Models.ArticlePanier", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "PanierId");

                    b.HasIndex("PanierId");

                    b.ToTable("ArticlePaniers");
                });

            modelBuilder.Entity("OzonExpress.Models.ArticleVente", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("VenteId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "VenteId");

                    b.HasIndex("VenteId");

                    b.ToTable("ArticleVentes");
                });

            modelBuilder.Entity("OzonExpress.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("OzonExpress.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OzonExpress.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("OzonExpress.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("OzonExpress.Models.Tarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Cout")
                        .HasColumnType("real");

                    b.Property<int>("VilleArrId")
                        .HasColumnType("int");

                    b.Property<int>("VilleDepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VilleArrId");

                    b.HasIndex("VilleDepId");

                    b.ToTable("Tarifs");
                });

            modelBuilder.Entity("OzonExpress.Models.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("OzonExpress.Models.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomVille")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("OzonExpress.Models.ArticlePanier", b =>
                {
                    b.HasOne("OzonExpress.Models.Article", "Article")
                        .WithMany("ArticlePaniers")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzonExpress.Models.Panier", "Panier")
                        .WithMany("ArticlePaniers")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("OzonExpress.Models.ArticleVente", b =>
                {
                    b.HasOne("OzonExpress.Models.Article", "Article")
                        .WithMany("ArticleVentes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OzonExpress.Models.Vente", "Vente")
                        .WithMany("ArticleVentes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("OzonExpress.Models.Tarif", b =>
                {
                    b.HasOne("OzonExpress.Models.Ville", "VilleArr")
                        .WithMany()
                        .HasForeignKey("VilleArrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OzonExpress.Models.Ville", "VilleDep")
                        .WithMany("Tarifs")
                        .HasForeignKey("VilleDepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VilleArr");

                    b.Navigation("VilleDep");
                });

            modelBuilder.Entity("OzonExpress.Models.Vente", b =>
                {
                    b.HasOne("OzonExpress.Models.Client", "Client")
                        .WithMany("Ventes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OzonExpress.Models.Article", b =>
                {
                    b.Navigation("ArticlePaniers");

                    b.Navigation("ArticleVentes");
                });

            modelBuilder.Entity("OzonExpress.Models.Client", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("OzonExpress.Models.Panier", b =>
                {
                    b.Navigation("ArticlePaniers");
                });

            modelBuilder.Entity("OzonExpress.Models.Vente", b =>
                {
                    b.Navigation("ArticleVentes");
                });

            modelBuilder.Entity("OzonExpress.Models.Ville", b =>
                {
                    b.Navigation("Tarifs");
                });
#pragma warning restore 612, 618
        }
    }
}
